# These are examples of PV config files : 

#NFS Ex
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name
spe:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOption:
    - hard
    - nfsvers=4.0
  nfs:
    path: /dir/path-on/nfs-server
    server: nfs-server-ip-@

---

#Google Cloud Ex 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  labels:
    failure-domain.beta.kubernetes.io/zone: us-centrall-a__us-centrall-b
spec:
  capacity:
    storage: 400Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4

---

#Local Storage Ex
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPlocity: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
    nodeAffinity:
      required:
        nodeSelectorTerms: 
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            volumes:
            - example-node
